import {
  Baby,
  BedDouble,
  BedSingle,
  Bike,
  Check,
  CigaretteOff,
  Coffee,
  CookingPot,
  Droplet,
  Fan,
  Flame,
  Footprints,
  Microwave,
  PawPrint,
  Refrigerator,
  Sandwich,
  Shirt,
  ShowerHead,
  Sofa,
  Soup,
  SquareParking,
  Table,
  Toilet,
  ToyBrick,
  Trees,
  Tv,
  Users,
  Utensils,
  WashingMachine,
  Wifi,
  Wind,
  type LucideIcon,
} from "lucide-react";

// Názvy musí přesně odpovídat možnostem sloupce "Ikona" v Notion databázi Texty.
const IKONY: Record<string, LucideIcon> = {
  "Oheň": Flame,
  "Stůl": Table,
  "Televize": Tv,
  "Nádobí": Utensils,
  "Lednice": Refrigerator,
  "Hrnec": CookingPot,
  "Mikrovlnka": Microwave,
  "Káva": Coffee,
  "Konvice": Soup,
  "Toustovač": Sandwich,
  "Dítě": Baby,
  "Postel": BedSingle,
  "Manželská postel": BedDouble,
  "WC": Toilet,
  "Hračky": ToyBrick,
  "Pračka": WashingMachine,
  "Sušička": Fan,
  "Fén": Wind,
  "Žehlička": Shirt,
  "Boty": Footprints,
  "Kolo": Bike,
  "WiFi": Wifi,
  "Parkování": SquareParking,
  "Nekuřácké": CigaretteOff,
  "Zvířata": PawPrint,
  "Sprcha": ShowerHead,
  "Pohovka": Sofa,
  "Lidé": Users,
  "Kapka": Droplet,
  "Stromy": Trees,
  "Fajfka": Check,
};

export const NAZVY_IKON = Object.keys(IKONY);

export function ikona(nazev: string | undefined, vychozi: LucideIcon = Check): LucideIcon {
  return (nazev && IKONY[nazev]) || vychozi;
}
